name: Run pytest on PR files

on:
  pull_request_target:
    types: [opened]  

jobs:

  basic_lime:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          ref: ${{ github.event.pull_request.head.sha }}

      - name: List files - should include changes / files from PR
        run: |
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup lime-green from pypi
        run: |
          python -m pip install --upgrade pip
          pip install lime-green

      - name: Run lime check
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          lime check

      - name: Run lime on sheets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd lime-sheets
          lime eval . -v